### ISSUE TITLE
Extreme slowdown in iEdit mode

### ISSUE THREAD

**Issue by jasonm23** [Malabarba/aggressive-indent-mode#47]
Not too surprisingly, iEdit's multiple edits will cause aggressive-indent-mode to slowdown Emacs to a crawl.

I think perhaps aggressive-indent should be aware of things like iEdit (Just speculating, but maybe cua rectangle and multiple cursors may have similar problems.) 

I guess suspending indentation until those specialised editing modes are inactive?

**Comment by Malabarba** [comment]
Yes. We already do that for `multiple-cursors`, `yasnippet`, and for some autocompletion systems, so it's just a matter of adding a check for iEdit and cua-rectangle.
Do you know if there is a variable that indicates these modes are active?

In general, it's good to have checks for any type of mode that sort of represents an "ongoing" edit. Not because of performance, but because these modes typically do not expect the buffer to be edited behind their back.

**Comment by jasonm23** [comment]
(when (bound-and-true-p iedit-mode)  ... )

Will detect it as active

**Comment by Malabarba** [comment]
Thanks, should be fixed now. If you install from GNU it'll be up tomorrow. From Melpa, a couple of hours.

**Comment by jasonm23** [comment]
Thanks very much
