### ISSUE TITLE
Way to not remove space before let/loop bindings in Clojure

### ISSUE THREAD

**Issue by sooheon** [Malabarba/aggressive-indent-mode#49]
Say I have the following:
```
(defn min-dot [xs ys]
  (let [a (sort > xs)
        b (sort < ys)]
    (apply + (map * a b))))
```
If I delete the b inside the let binding to change it, a-i-m automatically deletes the following empty space as well. This is fine in most cases, but it is a problem in conjunction with [lispy](https://github.com/abo-abo/lispy). I am wondering what I need to add to `aggressive-indent-dont-indent-if` so that a-i-m will not remove that space, I couldn't quite understand the example in the documentation.

**Comment by Malabarba** [comment]
That one's a little tricky, because it can be hard to identify that you're inside a let bindings vector.
Here's an example that just avoids indentation when you're inside a vector, you can try to make it more sophisticated.

    (add-to-list 'aggressive-indent-dont-indent-if
                 '(ignore-errors (up-list)
                                 (eq (char-after) ?\[)))

Another option would be to write the new variable name, and *then* delete the old name, instead of deleting it first.

Yet a third option would be to hit `C-o` (`open-line`) after deleting the variable name (`C-a` should work as well).

**Comment by sooheon** [comment]
Thanks for that example. One small change should be `(backward-up-list)` instead of `(up-list)`, but I get the idea. And yeah, just moving the point with C-a or C-b are all alternative options, as well.
